# -*- coding: utf-8 -*-
"""FID and LPIPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vn9ZQ56JHQznWbPiJ92UkppMImDSmPJe
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/

"""Unzip generated and ground-truth directories"""

!unzip "images.zip"

!pip install pytorch-fid

!pip install scipy==1.13.0

import scipy
scipy.__version__

"""Only run the cell below if image is being cropped"""

import os
from PIL import Image

def crop_center(directory):
    for filename in os.listdir(directory):
        if filename.endswith(".jpg") or filename.endswith(".png"):
            path = os.path.join(directory, filename)
            with Image.open(path) as img:
                width, height = img.size
                left = (width - 12)/2
                top = (height - 12)/2
                right = (width + 12)/2
                bottom = (height + 12)/2

                img_cropped = img.crop((left, top, right, bottom))

                img_cropped.save(os.path.join(directory, f"{filename}"))

crop_center('gt')
crop_center('inpainted')

!python -m pytorch_fid "inpainted" "gt"

!git clone https://github.com/fenglinglwb/MAT.git

"""Pull Mask Aware Transformer Repository (To be used for LPIPS evaluation)"""

# Commented out IPython magic to ensure Python compatibility.
# %cd MAT/

!pip install -rrequirements.txt

!pwd

!pip install lpips

# Commented out IPython magic to ensure Python compatibility.
# %cd ..

"""Rename files in directories to be the same

"""

import os

folder1 = 'inpainted'
folder2 = 'gen'

for filename in os.listdir(folder2):

        new_filename = filename.replace('Out_', 'In_')

        old_file = os.path.join(folder2, filename)
        new_file = os.path.join(folder2, new_filename)

        os.rename(old_file, new_file)
        print(f"Renamed '{filename}' to '{new_filename}'")

print("Renaming complete.")

"""Before running cell below, rename directories in cal_lpips.py to correpsond to gen and inpainted directories"""

!python MAT/evaluatoin/cal_lpips.py